Form order
Pudin-con-pasas-uwu/AdminPage pull request #38
Opened 2023-04-10 06:51 UTC by EdgarPerez07

Se creo el formulario para agregar orders
![image](https://user-images.githubusercontent.com/122763271/230844187-41892708-1d4e-4ebd-ac2b-ba11d623487e.png)

2023-04-10 07:27 UTC, Pudin-con-pasas-uwu commented
y en donde veo eso?? solo esta el jsx, ademas, ya tiene que tener la funcion post

2023-04-10 17:10 UTC, lokilaufeysonXD requested changes

2023-04-10 17:10 UTC, lokilaufeysonXD commented on src/components/FormOrders.jsx
> +        <div className="Formulario" id={styles.Formulario}>
esto lo puedes poner en un componente y llamarlo con un botón que sea el de agregar una nueva orden

2023-04-10 22:59 UTC, Creaky27 requested changes
el {styles.Formulario} debe de ir en className

2023-04-13 05:27 UTC, GerardoCasC requested changes
id es automático (sin input)
 el user_id es segun el que esté iniciando sesión
total amount es la suma del precio de todos los productos
Se deben pedir los productos y las cantidades, sumarlo y eso
order status es 1 por default (sebe ser un select)
No va a llevar imagen
El product debe ser un select donde salgan los prpductos de la bd
Y el precio se debe poner en automatico según el producto

2023-04-17 18:22 UTC, closed without merging